steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$_TAG'
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$_TAG'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '$_SERVICE'
      - '--image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$_TAG'
      - '--region=$_REGION'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=decision-journal-2026'

substitutions:
  _REGION: us-central1
  _REPO: decision-journal
  _SERVICE: decision-journal
  _TAG: latest

options:
  logging: CLOUD_LOGGING_ONLY
